version: '3.8'
services:
  counter:
    container_name: counter
    build: ./services/counter
    ports:
      - 3001:3001
    environment:
      - PORT=3001
    command: npm start
    networks:
      - local
  library:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - COUNTER_PORT=3001
      - COUNTER_HOST=counter
    command: npm start
    depends_on:
      - counter
    networks:
      - local
networks:
  local:
    driver: bridge
